run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - gocyclo
    - gofmt
    - goimports
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  max-same-issues: 5
  max-issues-per-linter: 0
  max-issues: 0