FROM golang:1.23-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

WORKDIR /app/cmd/sample-server
RUN go build -o /sample-server

FROM alpine:latest

WORKDIR /app/

COPY --from=builder /sample-server .

COPY ./config/relay.toml ./config/relay.toml

ENTRYPOINT ["./sample-server"]

CMD ["sample-server"]