version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123456
      POSTGRES_DB: outbox
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nats:
    image: nats:2.10
    container_name: nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"

  sample-server-1:
    build:
      context: .
      dockerfile: Dockerfile-sample-server
    container_name: sample-server-1
    restart: always
    depends_on:
      - postgres
      - nats
    environment:
      CONFIG_PATH: /app/config/sample-server.toml
      OUTBOX_DATABASE_DSN: postgres://admin:admin123456@postgres:5432/outbox?sslmode=disable
      OUTBOX_NATS_URL: nats://nats:4222
    ports:
      - "8081:8080"   # expose server-1 on localhost:8081
    volumes:
      - ./config:/app/config

  sample-server-2:
    build:
      context: .
      dockerfile: Dockerfile-sample-server
    container_name: sample-server-2
    restart: always
    depends_on:
      - postgres
      - nats
    environment:
      CONFIG_PATH: /app/config/sample-server.toml
      OUTBOX_DATABASE_DSN: postgres://admin:admin123456@postgres:5432/outbox?sslmode=disable
      OUTBOX_NATS_URL: nats://nats:4222
    ports:
      - "8082:8080"   # expose server-2 on localhost:8082
    volumes:
      - ./config:/app/config

  sample-consumer:
    build:
      context: .
      dockerfile: Dockerfile-sample-consumer
    container_name: sample-consumer
    restart: always
    depends_on:
      - nats
    environment:
      NATS_URL: "nats://nats:4222"
      NATS_TOPIC: "users"
    volumes:
      - ./config:/app/config

volumes:
  postgres_data:
